package com.brytech.pharmacist_service.enumeration;

public enum EventType {
    PRESCRIPTION_REVIEW_COMPLETED,
    DRUG_SHORTAGE,
    PRESCRIPTION_DISPENSED,
    PRESCRIPTION_ERROR,
    PRESCRIPTION_READY_FOR_PICKUP,
    INVENTORY_UPDATED,
    ORDER_PROCESSED,
    ORDER_CANCELED,
    PRESCRIPTION_VERIFIED,
    PRESCRIPTION_REJECTED,
    LOW_STOCK_ALERT,
    INVENTORY_DISPENSED,
    MESSAGE_SENT
}
