services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=brian
      - MONGO_INITDB_ROOT_PASSWORD=brian
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=brian
      - ME_CONFIG_MONGODB_ADMINPASSWORD=brian
      - ME_CONFIG_MONGODB_SERVER=mongodb
  volumes:
    mongo: {}