services:
  user-service-db-server:
    image: postgres:latest
    container_name: user-service-db-server
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]   # pg_isready
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - user-service-db-server-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: brycode
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5602:5432'

  user-service-db-admin:
    image: dpage/pgadmin4
    container_name: user-service-db-admin
    volumes:
      - user-service-db-admin-volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
    ports:
      - '5603:80'
    depends_on:
      user-service-db-server:
        condition: service_healthy

volumes:
  user-service-db-server-volume:
    driver: local
  user-service-db-admin-volume:
    driver: local
