
services:
  pharmacy-db-server:
    image: postgres:latest
    container_name: pharmacy-db-server
    healthcheck:
      test: pg_isready
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - pharmacy-db-server-volume:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB:${DATABASE_NAME}
    ports:
        - '5702:5432'

  pharmacy-db-admin:
    image: dpage/pgadmin4
    container_name: pharmacy-db-admin
    volumes:
      - pharmacy-db-admin-volume:/var/lib/pgadmin
    environment:
        - PGADMIN_DEFAULT_EMAIL=${DATABASE_ADMIN_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${DATABASE_ADMIN_PASSWORD}
    ports:
        - '5703:80'
    depends_on:
        pharmacy-db-server:
            condition: service_healthy

volumes:
    pharmacy-db-server-volume:
        driver: local
    pharmacy-db-admin-volume:
        driver: local
