
services:
  prescriptions-db-server:
    image: postgres:latest
    container_name: prescriptions-db-server
    healthcheck:
      test: pg_isready
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - prescriptions-db-server-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: brytech
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5502:5432'

  prescriptions-db-admin:
    image: dpage/pgadmin4
    container_name: prescriptions-db-admin
    volumes:
      - prescriptions-db-admin-volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
    ports:
      - '5503:80'
    depends_on:
      prescriptions-db-server:
        condition: service_healthy

volumes:
  prescriptions-db-server-volume:
    driver: local
  prescriptions-db-admin-volume:
    driver: local
