server:
  port: 8080
  servlet:
    context-path: /orders/api/v1
  error:
    include-message: always

spring:
  cache:
    type: redis
    redis:
      time-to-live: 60000
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:postgresql://localhost:6602/order_db
    username: brytech
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  kafka:
    bootstrap-servers: localhost:9092

  camel.component.kafka.configuration:
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.apache.kafka.common.serialization.StringSerializer
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    org.springframework.data.jpa: DEBUG

kafka:
  topic:
    payment-processed: payment.processed
    delivery-scheduled: delivery.scheduled
    prescription-validated: prescription.validated
    delivery-completed: delivery.completed
    inventory-updated: inventory.updated

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
