server:
  port: 8080
  servlet:
    context-path: /pharmacy/api/v1
  error:
    include-message: always

spring:
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 676359110882-2q3o27279u54v3chiqso5r38s7iusqjf.apps.googleusercontent.com
            clientSecret: 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

  kafka:
    bootstrap-servers: localhost:9092

  camel.component.kafka.configuration:
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.apache.kafka.common.serialization.StringSerializer
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: org.apache.kafka.common.serialization.StringDeserializer


logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    org.springframework.data.jpa: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

email:
  provider:
    properties:
      mail:
        smtp:
          host: smtp.gmail.com
          port: 587
          auth: true
          starttls:
            enable: true
    auth:
      username: eastendchemists@gmail.com
      password: ""

app:
  integrations:
    mpesa:
      consumer-key: YOUR_ACCESS_KEY
      consumer-secret: YOUR_ACCESS_TOKEN
      domain: https://sandbox.safaricom.co.ke
      shortCode: MPESA_SHORT_CODE
      express:
        shortCode: MPESA_SHORT_CODE