#spring.application.name=messaging-service

spring:
  data:
    mongodb:
      username: brian
      password: brian
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin
server:
  port: 8088
